<?php

namespace UserBundle\Repository;

/**
 * UtilisateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UtilisateurRepository extends \Doctrine\ORM\EntityRepository
{
	public function getLesPseudos($utilisateur)
	{
		$res = $this->getEntityManager()->createQuery(
	    "SELECT u.username
	    FROM UserBundle:Utilisateur u WHERE u != :utilisateur")
	    ->setParameter('utilisateur', $utilisateur)
		->getScalarResult();
		$pseudo = array();
		foreach ($res as $r) {
			$pseudo[] = $r['username'];
		}
		return $pseudo;
	}

	public function getTopAcheteur($nbr = 15)
	{
		return $this->getEntityManager()->createQuery(
	    "SELECT u
	    FROM UserBundle:Utilisateur u order by u.nbrAcheter DESC")
	    ->setMaxResults($nbr)
		->getArrayResult();
	}

	public function getTopVendeur($nbr = 10)
	{
		return $this->getEntityManager()->createQuery(
	    "SELECT u
	    FROM UserBundle:Utilisateur u order by u.nbrBon DESC, u.nbrVendu, u.nbrAnnonce DESC")
	    ->setMaxResults($nbr)
		->getArrayResult();
	}
}
