<?php

namespace ESSABA\AnnonceBundle\Repository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * AnnonceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnnonceRepository extends \Doctrine\ORM\EntityRepository
{
	public function rechercher($param, $className, $page=1, $maxperpage=12)
	{
		$repository = $this
    	->getEntityManager()
    	->getRepository('ESSABAAnnonceBundle:'.ucfirst($className));

		$query = $repository->createQueryBuilder('a');

		$query = $this->appliquerCritere($query, $param);



	    $query = $query->orderBy('a.created', 'DESC')
	    	->setFirstResult(($page-1) * $maxperpage)
            ->setMaxResults($maxperpage)
	    	->getQuery();
	    

		$annonces = $query->getResult();

		return $annonces;
	}

	public function getList($page=1, $maxperpage=12, $estOffre = null)
    {
        $q = $this->createQueryBuilder('a');
        if($estOffre !== null)
        {
        	$q = $q->andWhere('a.estOffre = :estOffre')
			->setParameter('estOffre', $estOffre);
        }
        $q = $q->orderBy('a.created', 'DESC');
 
        $q->setFirstResult(($page-1) * $maxperpage)
            ->setMaxResults($maxperpage);
 
        return new Paginator($q);
    }

    public function ajouterCritereTypeOffre($query, $estOffre)
    {
    	if($estOffre !== null)
        {
        	$query = $query->andWhere('a.estOffre = :estOffre')
			->setParameter('estOffre', $estOffre);
        }
        return $query;
    }

    public function getListByCateg($categ, $estOffre, $page=1, $maxperpage=12)
    {
        $query = $this->createQueryBuilder('a');
        $query = $query->join('a.sousCategorie', 's')
        ->andWhere('s.slug = :categ')
		->setParameter('categ', $categ);

		$query = $this->ajouterCritereTypeOffre($query, $estOffre);
		
        $query = $query->orderBy('a.created', 'DESC');
 
        $query->setFirstResult(($page-1) * $maxperpage)
            ->setMaxResults($maxperpage);
 
        return new Paginator($query);
    }

    function nbrAnnonce($estOffre = null)
	{
		$query = $this->createQueryBuilder('a')
		->select('COUNT(a)');

		if($estOffre !== null)
        {
        	$query = $query->andWhere('a.estOffre = :estOffre')
			->setParameter('estOffre', $estOffre);
        }
		
		return $query->getQuery()
		->getSingleScalarResult();
	}

	function nbrAnnonceByCateg($categ, $estOffre = null)
	{
		$query = $this->createQueryBuilder('a')
		->select('COUNT(a)');

        $query = $query->join('a.sousCategorie', 's')
        ->andWhere('s.slug = :categ')
		->setParameter('categ', $categ);
		$query = $this->ajouterCritereTypeOffre($query, $estOffre);
		return $query->getQuery()
		->getSingleScalarResult();
	}


	function nbrAnnonceRecherche($param, $className)
	{
		$repository = $this
    	->getEntityManager()
    	->getRepository('ESSABAAnnonceBundle:'.ucfirst($className));

    	$query = $repository->createQueryBuilder('a')
    			->select('COUNT(a)');

		$query = $this->appliquerCritere($query, $param);
		
		return $query->getQuery()
		->getSingleScalarResult();
	}








	public function appliquerCritere($query, $param)
	{
		if(isset($param['typeAnnonce']) && $param['typeAnnonce'] != "")
		{
			$estOffre = $param['typeAnnonce'] == 'offre';
			$query = $query->andWhere('a.estOffre = :estOffre')
		    ->setParameter('estOffre', $estOffre);	
		}
		if(isset($param['titre']) && $param['titre'] != "")
		{
			$query = $query->andWhere('a.titre like :titre')
		    ->setParameter('titre', '%'.$param['titre'].'%');	
		}
		if(isset($param['commune']) && $param['commune'] != null)
		{
			$query = $query->andWhere('a.commune = :commune')
		    ->setParameter('commune', $param['commune']);	
		}
		if(isset($param['min']) && $param['min'] != null)
		{
			$query = $query->andWhere('a.prix >= :min')
		    ->setParameter('min', $param['min']);	
		}
		if(isset($param['max']) && $param['max'] != null)
		{
			$query = $query->andWhere('a.prix <= :max')
		    ->setParameter('max', $param['max']);	
		}
		if(isset($param['categorie']) && $param['categorie'] != null)
		{
			$query = $query->andWhere('a.sousCategorie = :categorie')
		    ->setParameter('categorie', $param['categorie']);

		    switch ( $param['categorie']->getSlug() ) {
		    	case 'voiture':
		    		if(isset($param['kilometrageMin']) && $param['kilometrageMin'] != null)
					{
						$query = $query->andWhere('a.kilometrage >= :kilometrageMin')
					    ->setParameter('kilometrageMin', $param['kilometrageMin']);	
					}
					if(isset($param['kilometrageMax']) && $param['kilometrageMax'] != null)
					{
						$query = $query->andWhere('a.kilometrage <= :kilometrageMax')
					    ->setParameter('kilometrageMax', $param['kilometrageMax']);	
					}
					if(isset($param['marque']) && count($param['marque']) > 0)
					{
						$query = $query->andWhere('a.marque in(:marque)')
					    ->setParameter('marque', $param['marque']);
					}
					if(isset($param['boiteVitesse']) && count($param['boiteVitesse']) != null)
					{
						$query = $query->andWhere('a.boiteVitesse = :boiteVitesse')
					    ->setParameter('boiteVitesse', $param['boiteVitesse']);
					}
					if(isset($param['carburant']) && count($param['carburant']) != null)
					{
						$query = $query->andWhere('a.carburant = :carburant')
					    ->setParameter('carburant', $param['carburant']);
					}
		    		break;
		    	case 'moto':
		    		if(isset($param['kilometrageMin']) && $param['kilometrageMin'] != null)
					{
						$query = $query->andWhere('a.kilometrage >= :kilometrageMin')
					    ->setParameter('kilometrageMin', $param['kilometrageMin']);	
					}
					if(isset($param['kilometrageMax']) && $param['kilometrageMax'] != null)
					{
						$query = $query->andWhere('a.kilometrage <= :kilometrageMax')
					    ->setParameter('kilometrageMax', $param['kilometrageMax']);	
					}
		    		break;
		    	case ( $param['categorie']->getSlug() == 'chaussure' || $param['categorie']->getSlug() == 'vetements' ):
		    		if($param['categorie']->getSlug() == 'chaussure' && isset($param['pointure']) && $param['pointure'] != null)
					{
						$query = $query->andWhere('a.pointure = :pointure')
					    ->setParameter('pointure', $param['pointure']);	
					}
					if($param['categorie']->getSlug() == 'vetements' && isset($param['taille']) && $param['taille'] != null)
					{
						$query = $query->andWhere('a.taille = :taille')
					    ->setParameter('taille', $param['taille']);	
					}
					if(isset($param['couleur']) && $param['couleur'] != null)
					{
						$query = $query->andWhere('a.couleur = :couleur')
					    ->setParameter('couleur', $param['couleur']);	
					}
					if(isset($param['genre']) && $param['genre'] != null)
					{
						$query = $query->andWhere('a.genre = :genre')
					    ->setParameter('genre', $param['genre']);	
					}
		    		break;
		    	case ($param['categorie']->getSlug() == 'location' || $param['categorie']->getSlug() == 'vente-immobiliere') :
		    		if(isset($param['surfaceMin']) && $param['surfaceMin'] != null)
					{
						$query = $query->andWhere('a.surface >= :surfaceMin')
					    ->setParameter('surfaceMin', $param['surfaceMin']);	
					}
					if(isset($param['surfaceMax']) && $param['surfaceMax'] != null)
					{
						$query = $query->andWhere('a.surface <= :surfaceMax')
					    ->setParameter('surfaceMax', $param['surfaceMax']);	
					}
					if(isset($param['pieceMin']) && $param['pieceMin'] != null)
					{
						$query = $query->andWhere('a.piece >= :pieceMin')
					    ->setParameter('pieceMin', $param['pieceMin']);	
					}
					if(isset($param['pieceMax']) && $param['pieceMax'] != null)
					{
						$query = $query->andWhere('a.piece <= :pieceMax')
					    ->setParameter('pieceMax', $param['pieceMax']);	
					}
					if(isset($param['type']) && $param['type'] != null)
					{
						$query = $query->andWhere('a.type = :type')
					    ->setParameter('type', $param['type']);	
					}
					if($param['categorie']->getSlug() == 'location' && isset($param['meuble']) && $param['meuble'] != null)
					{
						$query = $query->andWhere('a.meuble = :meuble')
					    ->setParameter('meuble', $param['meuble']);	
					}
		    		break;
		    	case 'emploi-stage':
		    		if(isset($param['typeEmploi']) && $param['typeEmploi'] != null)
					{
						$query = $query->andWhere('a.type in (:typeEmploi)')
					    ->setParameter('typeEmploi', $param['typeEmploi']);	
					}
					if(isset($param['metier']) && $param['metier'] != null)
					{
						$query = $query->andWhere('a.metier = :metier')
					    ->setParameter('metier', $param['metier']);	
					}
		    		break;
		    	default:
		    		# code...
		    		break;
		    }
		}
		return $query;
	}





















}
