<?php

namespace ESSABA\AnnonceBundle\Repository;

/**
 * CategorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieRepository extends \Doctrine\ORM\EntityRepository
{
	function getAll(){
		return $this->createQueryBuilder('c')
			->select('c, s')
			->join('c.sousCategories', 's')
			->orderBy('c.ordre', 'ASC')
            ->getQuery()->getArrayResult();
	}
}