<?php

namespace ESSABA\AnnonceBundle\Repository;

/**
 * ChaussureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChaussureRepository extends \Doctrine\ORM\EntityRepository
{
}
