<?php

namespace ESSABA\AnnonceBundle\Repository;

/**
 * ConversationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConversationRepository extends \Doctrine\ORM\EntityRepository
{
	function getConvDeUtilisateur($idConversation, $utilisateur)
	{
		return $this->getEntityManager()->createQuery(
	    "SELECT c
	    FROM ESSABAAnnonceBundle:Conversation c
	    WHERE c.id = :conversation
	    and (c.utilisateur1 = :utilisateur or c.utilisateur2 = :utilisateur)"
		)
		->setParameter('conversation', $idConversation)
		->setParameter('utilisateur', $utilisateur)
		->getOneOrNullResult();
	}

	function voirConv($idConversation, $utilisateur)
	{
		return $conversations =  $this->getEntityManager()->createQuery(
	    "UPDATE ESSABAAnnonceBundle:Message  m SET m.vu = 1 WHERE m.conversation = :conversation and m.expediteur <> :utilisateur")
		->setParameter('conversation', $idConversation)
		->setParameter('utilisateur', $utilisateur)
		->execute();
	}

	function getConvForAnnonce($expediteur, $annonce)
	{
		$conv =  $this->getEntityManager()->createQuery(
	    "SELECT c
	    FROM ESSABAAnnonceBundle:Conversation c
	    WHERE c.annonce = :annonce
	    and (c.utilisateur1 = :expediteur or c.utilisateur2 = :expediteur or c.email = :expediteur)
	    ")
		->setParameter('annonce', $annonce)
		->setParameter('expediteur', $expediteur)
		->setMaxResults(1)
		->getOneOrNullResult();
		return $conv;
	}

	function getConversation($idConversation, $utilisateur)
	{
		$conversations = null;
		$conversations =  $this->getEntityManager()->createQuery(
	    "SELECT c.nom, c.tel, c.email, m.id, m.contenu, m.vu, m.created, IDENTITY(m.expediteur) as idExpediteur
	    FROM ESSABAAnnonceBundle:Message m join m.conversation c
	    WHERE m.conversation = :conversation
	    and (c.utilisateur1 = :utilisateur or c.utilisateur2 = :utilisateur)
		order by m.created")
		->setParameter('conversation', $idConversation)
		->setParameter('utilisateur', $utilisateur)
		->getArrayResult();
		return $conversations;
	}

	function getAllConversations($utilisateur)
	{
		$conv =  $this->getEntityManager()->createQuery(
		    "SELECT u1.image as image1, u2.image as image2, c.id as idConversation, m.id, 0 as estInconnu, a.titre as titreAnnonce, m.contenu, m.vu, 
		    		m.created, u1.username as nom1, u2.username as nom2, 0 as emailInconnu

		    FROM ESSABAAnnonceBundle:Message m join m.conversation c
		    	join c.annonce a join c.utilisateur1 u1 join c.utilisateur2 u2

		    WHERE m.created in (SELECT max(md.created) FROM ESSABAAnnonceBundle:Message md 
		    					join md.conversation cd
		    					where (cd.utilisateur1 = :utilisateur or cd.utilisateur2 = :utilisateur)
		    					group by cd.id)
			and (c.utilisateur1 = :utilisateur or c.utilisateur2 = :utilisateur)
			ORDER BY m.created DESC"
		)->setParameter('utilisateur', $utilisateur)->getArrayResult();

		

		$convAvecInconnu =  $this->getEntityManager()->createQuery(
		    "SELECT 'no' as image1, 'no' as image2, c.id as idConversation, m.id, 1 as estInconnu, a.titre as titreAnnonce, m.contenu, m.vu, 
		    		m.created, '".$utilisateur->getUsername()."' as nom1, c.nom as nom2, c.email as emailInconnu

		    FROM ESSABAAnnonceBundle:Message m join m.conversation c
		    	join c.annonce a

		    WHERE m.created in (SELECT max(md.created) FROM ESSABAAnnonceBundle:Message md 
		    					join md.conversation cd

		    					where (cd.utilisateur1 = :utilisateur or cd.utilisateur2 = :utilisateur)
		    					and (cd.utilisateur1 is null or cd.utilisateur2 is null)
		    					group by cd.id)
			and (c.utilisateur1 = :utilisateur or c.utilisateur2 = :utilisateur)
			and (c.utilisateur1 is null or c.utilisateur2 is null)
			ORDER BY m.created DESC"
		)->setParameter('utilisateur', $utilisateur)->getArrayResult();

		$conversations = array_merge($conv, $convAvecInconnu);

		usort($conversations, "ESSABA\AnnonceBundle\Repository\ConversationRepository::cmp");

		return $conversations;
	}

	static function cmp($a, $b)
	{
	    if ($a['created'] == $b['created']) {
	        return 0;
	    }
	    return ($a['created'] > $b['created']) ? -1 : 1;
	}
}
