<?php

namespace ESSABA\AnnonceBundle\Repository;

/**
 * NotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationRepository extends \Doctrine\ORM\EntityRepository
{
	function notifications($utilisateur){
		return $this->createQueryBuilder('n')
			->where('n.utilisateur = :utilisateur')
			->setParameter('utilisateur', $utilisateur)
			->orderBy('n.created', 'DESC')
            ->getQuery()->getArrayResult();
	}

	function getByLienAndUser($lien, $utilisateur){
		return $this->createQueryBuilder('n')
			->where('n.utilisateur = :utilisateur')
			->andWhere('n.lien = :lien')
			->setParameter('utilisateur', $utilisateur)
			->setParameter('lien', $lien)
			->setMaxResults(1)
            ->getQuery()->getOneOrNullResult();
	}

	function voirNotif($utilisateur){
		
		$this->createQueryBuilder('n')
        ->update()
        ->set('n.vu', true)
        ->where('n.utilisateur = :utilisateur')
        ->setParameter('utilisateur', $utilisateur)
        ->getQuery()->execute();

        // avec les date....
		/*$this->createQueryBuilder('n')
        ->delete()
        ->where('n.utilisateur = :utilisateur')
        ->setParameter('utilisateur', $utilisateur)
        ->getQuery()->execute();*/
	}

	function supprimerByConv($conv, $utilisateur){
		return $this->getEntityManager()->createQuery(
		    'DELETE ESSABAAnnonceBundle:Notification notif
		    WHERE notif.type=\'message\' and notif.utilisateur = :utilisateur and notif
		    in (Select IDENTITY(n.notification) from ESSABAAnnonceBundle:NotificationMeta n
		    WHERE n.cle = \'id_conv\' and n.valeur = :conv)'
		)->setParameter('conv', $conv)->setParameter('utilisateur', $utilisateur)->getSingleScalarResult();
	}

	/*function supprimerNotif($notif){
		$this->createQueryBuilder('n')
        ->delete()
        ->where('n = :notif')
        ->setParameter('notif', $notif)
        ->getQuery()->execute();
	}*/


	function nbrNouveau($utilisateur)
	{
        return $this->getEntityManager()->createQuery(
		    'SELECT count(n)
		    FROM ESSABAAnnonceBundle:Notification n
		    WHERE n.vu = false and n.utilisateur = :utilisateur'
		)->setParameter('utilisateur', $utilisateur)->getSingleScalarResult();
	}
}
