<?php

namespace ESSABA\AnnonceBundle\Repository;

/**
 * NotificationMetaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationMetaRepository extends \Doctrine\ORM\EntityRepository
{
	function getByNotifAndCle($cle, $notification){
		return $this->createQueryBuilder('n')
			->select('n.valeur')
			->where('n.notification = :notification')
			->andWhere('n.cle = :cle')
			->setParameter('notification', $notification)
			->setParameter('cle', $cle)
			->setMaxResults(1)
            ->getQuery()->getSingleScalarResult();
	}

	/*function supprimerByConv($conv){
		return $this->getEntityManager()->createQuery(
		    'DELETE ESSABAAnnonceBundle:NotificationMeta n
		    WHERE n.cle = \'id_conv\' and n.valeur = :conv'
		)->setParameter('conv', $conv)->getSingleScalarResult();
	}*/
}
