<?php

namespace ESSABA\AnnonceBundle\Repository;

/**
 * SousCategorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SousCategorieRepository extends \Doctrine\ORM\EntityRepository
{
	public function myFindAll()
	{
	  return $this
	    ->createQueryBuilder('a')
	    ->getQuery()
	    ->getResult()
	  ;
	}
}
