<?php

namespace ESSABA\AnnonceBundle\Repository;

/**
 * TypeEvenementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeEvenementRepository extends \Doctrine\ORM\EntityRepository
{
	function getAll(){
		return $this->createQueryBuilder('t')
			//->select('c, s')
			//->join('c.sousCategories', 's')
            ->getQuery()->getArrayResult();
	}
}
