<?php

namespace ESSABA\AnnonceBundle\Repository;

/**
 * VenteImobiliereRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VenteImobiliereRepository extends \Doctrine\ORM\EntityRepository
{
}
