<?php

namespace ESSABA\AnnonceBundle\Repository;

/**
 * VetementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VetementRepository extends \Doctrine\ORM\EntityRepository
{
}
